spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/brand
    username: phoneshop
    password: 11111111
  jpa:
    properties:
      hibernate:
      dialect:   org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8001
